env:
  node: true
  browser: true
  commonjs: true
  es6: true
  jquery: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
